### ISSUE TITLE
Default install css errors

### ISSUE THREAD

**Issue by devzvrm** [jgazeau/shadocs#10]
Maybe this is stupid - but following basic instructions and adding Bulma from NPM produces this result.

hugo v0.88.1+extended darwin/amd64 BuildDate=unknown
Error: Error building site: TOCSS: failed to transform "css/main.sass" (text/x-sass): SCSS processing failed: file "stdin", line 3, col 1: File to import not found or unreadable: bulma.

**Comment by jgazeau** [comment]
Hello,

Indeed one command is missing in the documentation. Bulma is used as submodule for the theme so to make it work here are the command you should use:
```shell
cd ${PROJECT_DIRECTORY}
git submodule add https://github.com/jgazeau/shadocs.git themes/shadocs
git submodule update --init --recursive
```

I'll update it in the next version to make it more clear.
