### ISSUE TITLE
Updated zip file for non-submodule implementation

### ISSUE THREAD

**Issue by sfjkastello** [jgazeau/shadocs#128]
### Question?

I would like to be able to use this theme, it is pretty incredible and the documentation is great!  Thank you!!

My deployment mechanism doesn't allow for submodules or hugo modules, so I am needing to create the themes/shadocs files and push during deployment.

I tried via downloading the zip but it seems to be missing quite a bit.  Is it possible this could be updated?  (example layout/partial/helpers)

I am trying via git clones of this project and the bulma project, but this is requiring identifying/removing all of the module/submodule pieces.

If there is another method that would be more simple please let me know.

Thank you.

**Comment by jgazeau** [comment]
Hi @sfjkastello ,

Glad you like the theme 😃 

Indeed in your case, I guess that going for the zip would be the best option if you cannot use git to pull the repository and sub-modules.
Also as you mention the latest release was created a long ago and the zip was not up-to-date.

I've created a [1.2.0](https://github.com/jgazeau/shadocs/releases/tag/1.2.0) of the theme and the new zip is published.
I'll try to release more often in the future. (Well... more than once a year 😄 ).

Regards,

Jordan.
