### ISSUE TITLE
[bug]: mobile version (tablet/mobile) menu not functioning as expected

### ISSUE THREAD

**Issue by malshar** [jgazeau/shadocs#144]
### Steps that lead to the issue

when generating the site and testing it the sidebar is always expanded on tablet and always minimized on the mobile phone. also the bottom collapse “button” not showing. this is also present in the documentation site when viewed on a mobile device or tablet. 

any suggestions for fixing it as i’m not a developer or will there be a fix soon?

### Expected behavior

expected the sidebar to be responsive but this issue is not resolved.

### Reproducer

the documentation site if viewed on a mobile or a tablet will show the issue.

**Comment by jgazeau** [comment]
Hi @malshar ,

Regarding the collapse/uncollapse sidebar, there is threshold for 1024px. Above 1024px width screens sidebar will be uncollapsed by default, and under 1024px width screens sidebar will be collapsed by default. Doing so is to avoid having a sidebar that take a lot of screen's space, especially on small screens where the sidebar is overlapping the main content.

On that point I will update the documentation website as it is not mentioned.

For the unavailable button, indeed I've check and there are few issues on mobile devices. Unfortunately I don't know for now where it come from.

I'll check as soon as I can, but It will not be in the coming days...probably few weeks.

**Comment by jgazeau** [comment]
Hello @malshar , I've actually have the time to check your issue and solve it.
Kr,

Jordan.
