### ISSUE TITLE
[feature_request]: Mouse scrolling in left sidebar

### ISSUE THREAD

**Issue by keybasegit** [jgazeau/shadocs#161]
### What is missing in the project?

[bug]: left sidebar with open menu on mobile version sliding down, showing all submenus. On linux, firefox, brave browser mouse scrolling doesn't work. The access to full menu is available through keyboard.

**Comment by keybasegit** [comment]
#### I am gratefull for the opportunity to use your theme. @Vlad

**Comment by jgazeau** [comment]
hi @keybasegit , not sure to understand your problem...
Can you be more explicit and provide a screenshot of your problem  ?
Regards.

**Comment by MasonXon** [comment]
hi, jgazeau,
look at this.
<img width="264" alt="图片" src="https://github.com/jgazeau/shadocs/assets/86297429/0c98d20b-3d19-4b73-939b-9a83da142781">

In the sidebar of this theme, if there are many articles, only the first few articles can be displayed, and none of the latter ones can be seen, so the sidebar should allow the mouse to scroll up and down to view more articles. One thing is whether the sidebar can be stretched horizontally. Some article titles will be longer and seem to be truncated, which is sometimes very inconvenient

**Comment by MasonXon** [comment]
These two problems have caused great limitations to the use at present. Is there any way to optimize it?

**Comment by MasonXon** [comment]
<img width="238" alt="图片" src="https://github.com/jgazeau/shadocs/assets/86297429/1e2fb7a6-cfb4-4260-b1a7-d6d73e4c5700">

I have tested it again, and it seems that the function is available, but it can only be used on the local server. Is there any restriction on this?

**Comment by jgazeau** [comment]
Hi @xiangma0510 , there might have been an issue on a previous commit indeed. I have created a [1.3.0](https://github.com/jgazeau/shadocs/releases/tag/1.3.0) version, so you can wether get this one or use the latest commit on the main branch (depending on your workflow).

**Comment by MasonXon** [comment]
Already fixed, thanks a lot.
