### ISSUE TITLE
[bug]: toc is not scrolling page if openapi is contained

### ISSUE THREAD

**Issue by McShelby** [jgazeau/shadocs#173]
### Steps that lead to the issue

Open https://shadocs.netlify.app/shortcodes/openapi/
Press some link inside "On this page"

### Expected behavior

The pages should scroll to the fragment

### Reproducer

See above

### Solution?

Add 

````javascript
<script>window.noZensmooth = true;</script>
````

before loading the swagger-ui javascript files.

**Comment by McShelby** [comment]
As I shamelessly copied lots of your code for my own implementation of an `openapi` shortcode, I've stumbled across this bug also in your code.

So I thought at least, I could give back a bit. See McShelby/hugo-theme-relearn#526

**Comment by jgazeau** [comment]
Hi @McShelby , sorry for the delay and thanks a lot for the heads up.
I'll correct this asap.
