### ISSUE TITLE
[bug]: Wrong link for "taxonomies"

### ISSUE THREAD

**Issue by ln5** [jgazeau/shadocs#176]
### Steps that lead to the issue

x

### Expected behavior

x

### Reproducer

x

### Solution?

`s|https://gohugo.io/content-management/multilingual|https://gohugo.io/content-management/taxonomies|1 exampleSite/content/english/functionalities/taxonomies.md`

**Comment by jgazeau** [comment]
Hi @ln5 , Can you be more specific ?
