### ISSUE TITLE
[bug]: exampleSite fails with latest hugo version 0.112.5

### ISSUE THREAD

**Issue by deining** [jgazeau/shadocs#179]
### Steps that lead to the issue

From the root of `shadocs` repo:

```
cd exampleSite
hugo server
```

An error is thrown:

```
Error: error building site: "/home/andreas/shadocs/exampleSite/content/english/shortcodes/snippet.md:69:13": failed to render shortcode "snippet": failed to process shortcode: "/home/andreas/shadocs/layouts/shortcodes/snippet.html:115:89": execute of template failed: template: shortcodes/snippet.html:115:89: executing "getSnippetContent" at <.context.Page.RenderString>: error calling RenderString: "/home/andreas/shadocs/exampleSite/content/english/shortcodes/snippet.md:1:1": failed to parse Markdown attributes; you may need to quote the values
```

### Expected behavior

No error, site should be served.

### Reproducer

This this failed [deployment log](https://app.netlify.com/sites/shadocs/deploys/6474dd942904db00084d03ca) on Netlify, belonging to #178.

### Solution?

This is most likely related to this open [isssue](https://github.com/gohugoio/hugo/issues/10835#issuecomment-1564849237) in the repo of Hugo SSG. You may wait for a fix or implement a workaround.

**Comment by jgazeau** [comment]
Hi @deining ,
I've made a fix for that, you also bump the hugo version to 0.112.5.
