### ISSUE TITLE
[bug]: Home page urls using relative paths are not working properly

### ISSUE THREAD

**Issue by MasonXon** [jgazeau/shadocs#195]
### Steps that lead to the issue

1. Publish the exampleSite with gitlab pages, you will get a access url like: `https://site.pages.example.com/homepage/`
2. access url using it
3. click globalLogo, it will return 404, redirected to `https://site.pages.example.com/`, but not `https://site.pages.example.com/homepage/`

### Expected behavior

You can normally jump to the home page with a relative path

### Reproducer

1. publish exampleSites using gitlab pages or github pages
2. access pages
3. click globalLogo

**Comment by MasonXon** [comment]
for example：
In your site: 
    homePage always https://shadocs.netlify.app/, if it will be https://shadocs.netlify.app/main,when it click logo, it will return 404
<img width="1818" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/9c83de4b-2ce0-4994-97dd-3fc9e59c4325">

**Comment by MasonXon** [comment]
The following also has the same problem：
<img width="1868" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/1dabee5d-98d3-40fc-bb0c-3882418c72d3">

**Comment by jgazeau** [comment]
Hi @xiangma0510 , indeed my bad.
Fix is undergoing and will be available soon.
