### ISSUE TITLE
[bug]: mermaid cannot be rendered

### ISSUE THREAD

**Issue by MasonXon** [jgazeau/shadocs#206]
### Steps that lead to the issue

<img width="842" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/95da3d18-5011-45ce-ab83-40b2d32f8c35">

This is the code from pages with theme shadocs.

### Expected behavior

<img width="860" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/dc5090ac-8b8b-4fe3-83e7-27215f8aa911">

this is rendered using typora

### Reproducer

It seems no one can be rendered in my environment, if there is something i should config?

**Comment by jgazeau** [comment]
hi @xiangma0510 ,
Can you be more explicit ?
What is the markdown code you are using ?

If you follow this [page](https://shadocs.netlify.app/functionalities/mermaid/), I explain how you should use the mermaid code to be displayed and take it into account. 
You should put it into a fenced code block like in the example. e.g:
````
```mermaid
graph TB
    subgraph Étape 2
    b1(Action 2.1) --> b2(Action 2.2)
    end
    subgraph Étape 1
    a1(Action 1.1) --> a2(Action 1.2)
    end
```
````

**Comment by MasonXon** [comment]
I use the same code block with you. but it not
<img width="850" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/4340cddd-9645-426a-8379-0c71180ae318">

**Comment by MasonXon** [comment]
This is the source code.
<img width="934" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/2f22965e-e1a0-4209-aee5-69ac4d2f925a">

**Comment by jgazeau** [comment]
I'm sorry but I still need more information to help you. Can you provide a reproducer ?

**Comment by MasonXon** [comment]
Sorry, I found the problem, it was the params I added before.
<img width="562" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/2a62bed2-edc8-4285-81d5-4fa75d9e58e5">

**Comment by MasonXon** [comment]
There is a another question, If I can change background color with svg rendered. current color looks a bit difficult, where can this be adjusted? 
<img width="1335" alt="image" src="https://github.com/jgazeau/shadocs/assets/86297429/c166a69e-0b44-4e25-94c0-b2b6bea50e18">

**Comment by jgazeau** [comment]
The mermaid theme used in shadocs is the dark one. But I think you can adjust the background color directly within your chart. You can ask it on mermaid community for more help. If it needs to be changed in the shadocs theme, please open a new feature.
