### ISSUE TITLE
:magic_wand:  [question]: Documentation to help implement the "Theme onBoarding" User Experience :star_struck: 

### ISSUE THREAD

**Issue by adriens** [jgazeau/shadocs#265]
### Question?

# :grey_question: About

We have built an automated data-driven wiki that, at the end, relies on HUGO for the rendering and gh-pages on the hosting. We are really very happy with that... and we have chosen your theme.

We are now preparing the content & documentation to onboard developers on this documentation (blog post to be released next week as well as a dedicated YT video).

And I wonder how you did the amazing onboarding user experience : 

![image](https://github.com/user-attachments/assets/a87a72ee-17e9-480e-92a5-517e2a04decd)
![image](https://github.com/user-attachments/assets/4de90277-bbc9-4c2b-b4bb-2b63c34eee16)
![image](https://github.com/user-attachments/assets/e382c73d-dbb3-4d15-afe7-6272caf50d5b)

**:point_right: This would help me point people the most important resources and make UX and DevEx even better.**

# :dart: Actions

- Provide the guidelines/howto to implement that (feedbacks guarenteed)

**Comment by jgazeau** [comment]
Hi @adriens ,

Sorry for the delay and thanks for using the theme, glad you like it.

For the onboarding experience, I'm actually using a intro shortcode based on intro.js.
You can check the [shortcode documentation](https://jgazeau.github.io/shadocs/shortcodes/intro/) and also check the [theme onboard implementation](https://github.com/jgazeau/shadocs/blob/main/exampleSite/content/english/_index.md?plain=1), it should be enough for you to start.
Also FYI, I'm using some [helper functions](https://jgazeau.github.io/shadocs/functionalities/helpers_js/) I'm providing in the theme globally to be able to do some actions (collapse/uncollapse sidebar, toggle TOC, ...)

**Comment by adriens** [comment]
> Sorry for the delay and thanks for using the theme, glad you like it.

No porblem, glad to have he feedback...especially when it answsers the question :star_struck: 

Below the exact resources I was looking for but that I could not find by meyself, thanks a lot for having pointed them to me :pray:  : 

![image](https://github.com/user-attachments/assets/62750320-e9f0-4826-bd04-79635ed8c195)

![image](https://github.com/user-attachments/assets/583f5928-e362-4ef8-8eb2-d75cedee7248)

I'll make an internal issue to implement it.

Keep going : your theme is really good :sunglasses:
