### ISSUE TITLE
themesdir  = "../.." causing problems

### ISSUE THREAD

**Issue by realB12** [jgazeau/shadocs#39]
Have installed current Shadocs Theme from GitHub into most updated HUGO instance on my local Windows10 machine. 
Have then copied the Theme's Example Project intp the root-folder

**Problem**: 

When hugo generating I have got the following error message: 

`"C:\me\...\TestSite\content\english\_index.md:8:1": failed to extract shortcode: template for shortcode "intro" not found"`

This error is most probably due to a path issue: because the `intro.md` template file is available but cannot be found. 

**Solution:**

In config.toml - which I have copied form the Example Projcet as well - I have removed the `themesdir = "../.."` statement. After this all fine

**Question:**
Not sure whether this is really the way to go. Could you pls have a look into this. Thanks.

**Comment by jgazeau** [comment]
Indeed, the `themesDir` sets inside the config.toml of the exampleSite is only relevant for the shadocs project tree structure. 

In your case, as you have a user structure it should definitely be changed appropriately. I have mentionned it in the [configuration page](https://shadocs.netlify.app/theme/configuration/) by pointing it to the standard Hugo documentation. I know that it is not really explicit but as it is a standard Hugo property, it would not make sense to explain it in the theme.

But one thing that could be made is to provide another repo as an example that use this theme. If the theme is more widely used in the future, I'll think about creating kind of a showcase section containing links to project that use the theme. This way it will be easier for users to have concrete examples.
