### ISSUE TITLE
Just saying "THANKY YOU": GREAT WORK

### ISSUE THREAD

**Issue by realB12** [jgazeau/shadocs#40]
Dear Jordan, 
I just wanted to say that I am absolutely delighted with your work. 
I was looking now for 2 years for the best Hugo Theme I could use for my many documentation sets I have created along many large scale projects for customers and private one. Your ShaDocs Theme is the best for my purpose. Especially the functionality is unbeaten. So, I will fully build on this and I am hoping that many others will use your excellent work as well. 
Wish you all the best and whenever you need a reference, count on me. 
Your work is simply great. 
Thank you!!

**Comment by jgazeau** [comment]
Hello @realB12 ,

Well, thank you very much 😃 , and very glad that you like the theme and that it fit your needs.
I would accept to grab a beer if one day I come to Zurich 😆 .
Kr,
