### ISSUE TITLE
Logo link duplicates when base URL contains path

### ISSUE THREAD

**Issue by Anaminus** [jgazeau/shadocs#44]
When the base URL of the website is configured with a path, the path portion of the logo's URL will be duplicated.

**Reproduction:**
1. In `config.toml`, set the `baseURL` to `"https://example.com/foo/bar"`.
2. Start `hugo serve`.
3. Navigate to http://localhost:1313/foo/bar/.
4. Click on the logo.

The result is that the page incorrectly navigates to http://localhost:1313/foo/bar/foo/bar/ instead of http://localhost:1313/foo/bar/.

The problem occurs in [layouts/partials/theme/logo.html](https://github.com/jgazeau/shadocs/blob/85d05fe6819a8e74f1400adc92d5530650390138/layouts/partials/theme/logo.html#L2-L5), and is likely caused by passing the `.Site.Home.RelPermalink` variable to the `relLangURL` function. Because `relLangURL` will already include the root, it would appear to be sufficient to pass an empty string instead. For example:

```text
{{"" | relLangURL}}
```

**Comment by jgazeau** [comment]
Thanks @Anaminus and sorry for the delay,
Indeed, url is correct now. (Problem was also in 404.html).
