### ISSUE TITLE
Poor contrast for links within info alerts

### ISSUE THREAD

**Issue by Anaminus** [jgazeau/shadocs#45]
Because both info alerts and links are blue, a link within an info alert has poor readability. For example, on the page for [shortcodes](https://shadocs.netlify.app/shortcodes/):

![firefox_BJb6oAAGSZ](https://user-images.githubusercontent.com/918097/165982498-f9eb8ea4-b314-4f46-8bfc-666b39bf8d80.png)

**Comment by jgazeau** [comment]
Hello @Anaminus,

Sorry for the delay. Indeed this shortcode definitely require a better contrast.
I've put something lighter which also be more relevant as an info shortcode (previous blue was king of too blue 😄)
