### ISSUE TITLE
Config for table of contents

### ISSUE THREAD

**Issue by pensivedog** [jgazeau/shadocs#63]
This is part support question and part feature request.

Is there a way to disable the table of contents, sitewide or at the page level? I'd like for the content of some pages to span the full page width, and only use the TOC for pages with long text content.

I'm able to achieve this sitewide by changing `{{$.Scratch.Set "isToc" true}}` to `{{$.Scratch.Set "isToc" false}}` in the content.html partial, then changing the width in css from `calc(100% - 300px)` to `100%.` Is there a better way to do this? And is there a way to do it at the page, rather than site, level?

It would be nice to have a sitewide option in the config params, as well as a way to enable/disable the TOC at the page level by configuring it in the page metadata.

If this configurability can be achieved, it would then be even better to also let the TOC be collapsible like the left sidebar on pages where it's enabled.

**Comment by jgazeau** [comment]
Indeed, this could be a good feature to add:
* include a global option to disable or enable the TOC sidewide 
* include a front matter option taking precedence over the sidewide option
* homepage will still remains without TOC in any case

Regarding a collapsible TOC, it could also be nice to have it, especially for medium screen sized where the TOC can take a lot of place.
The behavior would be the same as the actual sidebar:
* uncollapsed by default
* bottom right button to collapse/uncollapse TOC
* compare to sidebar no icons will be displayed (probably just a TOC icon, or a vertical text, I'll check what is more user friendly)

**Comment by pensivedog** [comment]
A few additional considerations for this:

1. With a collapsible TOC, it will also be handy to be able to configure it to be expanded or collapsed by default
2. With a disabled TOC, the page categories and tags will also not be displayed. One possible way to keep them available for users could be to include them at the top of the content area, similar to how they're displayed [here](https://learn.netlify.app/en/cont/tags/)
3. Although it's a separate feature request, it would also be neat for Shadocs to have an optional top bar with breadcrumbs and an edit link, as in the above-linked example

**Comment by jgazeau** [comment]
Actually the I agree with you that it could be possible but the purpose of this theme is not to manage all possibilities and behaviors.
* For the first point, same as the collapsible sidebar, it is the default management. If people don't want to collapse the sidebar.....then just don't click on it :)
* for the second point, the theme hugo-theme-learn is using it's own way to manage the categories. For shadocs, the aim is to provide them inside the TOC sidebar, and also manage all taxonomies that can be declared in the website (all terms are grouped by taxonomies for each pages which is more user-frendly). The point is not to overcharged the main content view with all of these informations as they are already available somewhere else.
* for the third point, indeed it can be part of a new feature. feel free to open a new issue for that

**Comment by pensivedog** [comment]
Yes, you are totally right. Those requests were too design-specific for this issue queue. Apologies!

**Comment by jgazeau** [comment]
@pensivedog , toc is now collapsible and configurable. You can rely on the [following configuration](https://shadocs.netlify.app/functionalities/toc/) to do so 😃

**Comment by pensivedog** [comment]
Looks great!
