### ISSUE TITLE
Trouble rendering plotly plot

### ISSUE THREAD

**Issue by pensivedog** [jgazeau/shadocs#67]
This is described in a separate blogdown issue [here](https://github.com/rstudio/blogdown/issues/712#issuecomment-1173483423), but perhaps it's a Shadocs issue?

Plotly plots generated in RMarkdown using the blogdown package are only rendering in Shadocs if the file is named `index.Rmd` and lives in its own directory, e.g., `test/index.Rmd`.

Using other themes, plotly plots render properly from `anywhere/anything.Rmd`.

Any idea what could be causing this?

**Comment by jgazeau** [comment]
`Rmd` is a specific format files used by the R studio apparently. 
It is not managed by Hugo and therefore Hugo themes does not manage them. I guess that some file manipulation and conversion are occuring on blogdown side to convert Rmd to md files ?
I suggest you to wait for their answer.
