### ISSUE TITLE
Table styling issue

### ISSUE THREAD

**Issue by pensivedog** [jgazeau/shadocs#69]
Table styling defined in `assets/sass/theme/global.sass` interferes with charts rendered by some standard charting tools like highcharts. Rather than impose specific table styling on all tables, might it be better to just apply it to a class, such as .shadocs-table? I guess this approach would require adding that class to each table in the current shadocs documentation, but it seems this would allow for more generic use of the shadocs theme.

**Comment by jgazeau** [comment]
Hi @pensivedog ,
Actually it is not possible to add directly from Hugo, a class on the table generated html (only a few [render hook](https://gohugo.io/templates/render-hooks/) are availables). Furthermore a lot of library exists to manage tables or charts, and managing all of their specificities inside one single theme would be unmaitainable and irrelevant.
But indeed a new shortcode, to use charts within shadocs would be a good idea. I'll create an issue to log that.

To solve your specific issue, in your case you can extend the theme and put your own css rules to override the default one. Just like in the exampleSite by adding a specific [css file](https://github.com/jgazeau/shadocs/blob/main/exampleSite/assets/css/shortcuts.css) and add the inclusion of this file in the [config.toml](https://github.com/jgazeau/shadocs/blob/main/exampleSite/config.toml#L95)

Also remember to provide a reproducer if you have any trouble. It helps a lot to understand precisely and clearly what is your issue with the project 😉

**Comment by pensivedog** [comment]
Thank you for the reply! I'm using shadocs with the blogdown package in RStudio, so my reproducer would be kind of case-specific, but I think the issue is rather general. Common plotting libraries and tools like highcharts include their own styling, and some use `<table>` elements in some plot layouts. Here's an [example](https://www.highcharts.com/demo/column-basic) of a highcharts chart in which the tooltip displayed on hover appears as a table. In the version of this chart created in blogdown/shadocs, the tooltip is broken because shadocs table styles are being applied.

I already have a child theme setup allowing me to override shadocs theme styles without changing any files in the shadocs theme directory, so I can benefit from future upstream updates. But for this table issue, the only way I've found to remove the shadocs table styling is to comment out or remove the following lines from `assets/sass/theme/global.sass`:

```
table:not([style])
  margin: $content-item-margin
  border-collapse: collapse
  table-layout: fixed
  border-spacing: 0
  width: 100%
  blockquote
    background: smooth-color($content-background, 10)
    blockquote
      background: smooth-color($content-background, 20)
  th
    color: findColorInvert($content-table-color)
    background: $content-table-color
  th,
  td
    border: 1px solid smooth-color($content-table-color, 25)
    padding: $theme-gap-medium-size $theme-gap-large-size
    vertical-align: middle
    overflow: auto
  td
    color: $content-writing-color
  tbody
    tr
      &:nth-of-type(odd)
        background: smooth-color($content-background, 10)
```

But then to build properly, I must also include all the other files and subdirectories of `assets/sass/theme/` in my child theme, which I have no need to override.

Besides highcharts, I've had this issue with other charts that include `<table>` elements, so I need a way avoid those shadocs styles being applied to all tables. But it also would be nice to keep the consistent shadocs table styling available for use in standard text/non-chart table contexts, hence my initial thought to store it in a class.

Any ideas?

**Comment by jgazeau** [comment]
Indeed the purpose is not to update directly the theme files, because you'll loose the advantages of extending the theme.

Regarding the css rules, as stated for now there are no solutions in Hugo other than override the default rules provided by the theme (using for example the `all: unset` css rule and creating your own css file), or adapting the rules defined from the library that you are using.
Well the theme could disable all tables css rules but it would obviously not be a theme anymore.
FYI: here is the [issue](https://github.com/gohugoio/hugo/issues/9316) that has been opened on Hugo side, but not sure it is urgent and planned.

**Comment by pensivedog** [comment]
Understood. Thank you for clarifying!
