### ISSUE TITLE
[feature_request]: Improve responsive layout

### ISSUE THREAD

**Issue by Anaminus** [jgazeau/shadocs#72]
### What is missing in the theme?

On the smallest `desktop` screen size (just above 1024px), I feel that the content of a page is squeezed too much by the sidebar and the Table of Contents:

![Just above 1024px](https://user-images.githubusercontent.com/918097/179643877-1da9f1ce-cf18-4b80-bb01-6c9d3aac976f.png)

Moreover, the difference between just above 1024px and just below is rather large:

![Just below 1024px](https://user-images.githubusercontent.com/918097/179643893-5a5aba34-04a8-4947-be0d-bc9c0e223843.png)

First, I think the ToC should have the same behavior as the sidebar, where on smaller screen sizes, it is collapsed by default, and floats over the page content when expanded.

Second, I think layout responsiveness would be improved by having one panel collapse before the other. The lower-priority panel would begin collapsing on `desktop` screen sizes, while the higher-priority panel would begin collapsing on `touch` screen sizes.

I'm not sure which is objectively better, but personally, I like having the ToC collapsed first, which is similar to the workaround I've been using for my website ([example](https://anaminus.github.io/RBXMK_DOC_TEMPORARY_DO_NOT_USE_OR_YOU_WILL_BE_FIRED/overview/)).

**Comment by jgazeau** [comment]
Hi @Anaminus ,
Sorry for the delay.
Indeed, I agree that the difference between just below desktop, and just above desktop is too heavy and should be more smooth.
So based on you're suggestion here are the keypoints:
* sidebar collapse threshold = 1024px (under which the navbar is collapsed)
* toc collapse threshold = 1280px (under which the toc is collapsed and also overlapse the main content)
* toc not visible = 1024px (under which the toc is not visible)

I would put 1280px for the threshold of the toc to match the most common screen width.
Let me know if you agree on that, I'll do it ASAIC.

Regards,

**Comment by Anaminus** [comment]
1280px seems fine, but note that Bulma has a [breakpoint](https://bulma.io/documentation/overview/responsiveness/#breakpoints) at 1216px ("widescreen") which might be easier to use, and more consistent with the rest of the theme.

I think that having the overlapping behavior for the toc would be enough to allow it to be visible at all times. That is, it doesn't need to be hidden below 1024px. This would make navigating pages on mobile a lot easier, and would allow a page's taxonomies to remain available.

**Comment by jgazeau** [comment]
Hi @Anaminus , 
Indeed I've checked and actually it would make more sense to follow the bulma size breakpoints, and also it look more smooth at that size. Also as you pointed, no need to hide the toc as it is now collapsed by default on small screen. 
I've implemented the changes and it'll soon be available in the master.
